# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(1017, 765)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        main_window.setFont(font)
        main_window.setMouseTracking(True)
        main_window.setFocusPolicy(QtCore.Qt.NoFocus)
        main_window.setLayoutDirection(QtCore.Qt.RightToLeft)
        main_window.setAutoFillBackground(True)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        main_window.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tbx_action = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbx_action.setGeometry(QtCore.QRect(450, 150, 521, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tbx_action.setFont(font)
        self.tbx_action.setAutoFillBackground(True)
        self.tbx_action.setObjectName("tbx_action")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setEnabled(True)
        self.btn_start.setGeometry(QtCore.QRect(450, 30, 91, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_start.setFont(font)
        self.btn_start.setAutoDefault(False)
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setEnabled(True)
        self.btn_stop.setGeometry(QtCore.QRect(560, 30, 91, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_stop.setFont(font)
        self.btn_stop.setAutoDefault(False)
        self.btn_stop.setObjectName("btn_stop")
        self.btn_feeding = QtWidgets.QPushButton(self.centralwidget)
        self.btn_feeding.setEnabled(True)
        self.btn_feeding.setGeometry(QtCore.QRect(660, 30, 101, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_feeding.setFont(font)
        self.btn_feeding.setAutoDefault(False)
        self.btn_feeding.setObjectName("btn_feeding")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setEnabled(True)
        self.btn_play.setGeometry(QtCore.QRect(770, 30, 101, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_play.setFont(font)
        self.btn_play.setAutoDefault(False)
        self.btn_play.setObjectName("btn_play")
        self.btn_cheer_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cheer_up.setEnabled(True)
        self.btn_cheer_up.setGeometry(QtCore.QRect(880, 30, 91, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_cheer_up.setFont(font)
        self.btn_cheer_up.setAutoDefault(False)
        self.btn_cheer_up.setObjectName("btn_cheer_up")
        self.conimal_view = QtWidgets.QLabel(self.centralwidget)
        self.conimal_view.setGeometry(QtCore.QRect(40, 20, 331, 291))
        self.conimal_view.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.conimal_view.setAutoFillBackground(True)
        self.conimal_view.setText("")
        self.conimal_view.setPixmap(QtGui.QPixmap(":/cat.png"))
        self.conimal_view.setAlignment(QtCore.Qt.AlignCenter)
        self.conimal_view.setObjectName("conimal_view")
        self.lbl_action = QtWidgets.QLabel(self.centralwidget)
        self.lbl_action.setGeometry(QtCore.QRect(650, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_action.setFont(font)
        self.lbl_action.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_action.setObjectName("lbl_action")
        self.lst_nero_item = QtWidgets.QListView(self.centralwidget)
        self.lst_nero_item.setGeometry(QtCore.QRect(450, 500, 521, 231))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lst_nero_item.setFont(font)
        self.lst_nero_item.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lst_nero_item.setLineWidth(3)
        self.lst_nero_item.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.lst_nero_item.setDragEnabled(True)
        self.lst_nero_item.setObjectName("lst_nero_item")
        self.lbl_item = QtWidgets.QLabel(self.centralwidget)
        self.lbl_item.setGeometry(QtCore.QRect(560, 460, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_item.setFont(font)
        self.lbl_item.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_item.setObjectName("lbl_item")
        self.pbr_appetite = QtWidgets.QProgressBar(self.centralwidget)
        self.pbr_appetite.setGeometry(QtCore.QRect(30, 360, 361, 31))
        self.pbr_appetite.setProperty("value", 100)
        self.pbr_appetite.setObjectName("pbr_appetite")
        self.pbr_affection = QtWidgets.QProgressBar(self.centralwidget)
        self.pbr_affection.setGeometry(QtCore.QRect(30, 430, 361, 31))
        self.pbr_affection.setProperty("value", 100)
        self.pbr_affection.setObjectName("pbr_affection")
        self.pbr_health = QtWidgets.QProgressBar(self.centralwidget)
        self.pbr_health.setGeometry(QtCore.QRect(30, 510, 361, 31))
        self.pbr_health.setProperty("value", 100)
        self.pbr_health.setInvertedAppearance(False)
        self.pbr_health.setObjectName("pbr_health")
        self.tbx_status = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbx_status.setGeometry(QtCore.QRect(30, 600, 361, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tbx_status.setFont(font)
        self.tbx_status.setAutoFillBackground(True)
        self.tbx_status.setObjectName("tbx_status")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(150, 560, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status.setFont(font)
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 330, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 400, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 480, 81, 21))
        self.label_3.setObjectName("label_3")
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.btn_stop.clicked.connect(self.tbx_action.clear)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Conimal"))
        self.tbx_action.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'D2Coding\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_start.setText(_translate("main_window", "시작"))
        self.btn_stop.setText(_translate("main_window", "중지"))
        self.btn_feeding.setText(_translate("main_window", "밥주기"))
        self.btn_play.setText(_translate("main_window", "놀아주기"))
        self.btn_cheer_up.setText(_translate("main_window", "응원"))
        self.lbl_action.setText(_translate("main_window", "action"))
        self.lbl_item.setText(_translate("main_window", "nero가 훔쳐온 것들"))
        self.pbr_appetite.setFormat(_translate("main_window", "%p%"))
        self.pbr_affection.setFormat(_translate("main_window", "%p%"))
        self.pbr_health.setFormat(_translate("main_window", "%p%"))
        self.tbx_status.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'D2Coding\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lbl_status.setText(_translate("main_window", "status"))
        self.label.setText(_translate("main_window", "식욕"))
        self.label_2.setText(_translate("main_window", "애정욕"))
        self.label_3.setText(_translate("main_window", "건강"))

from image_resource import cat_eating_rc
from image_resource import cat_grooming_rc
from image_resource import cat_rc
from image_resource import cat_rooling_rc
from image_resource import catw_rc
from image_resource import cat_cheer_rc
from image_resource import cat_play_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

