# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\pycharm_project\conimal\ui_source\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(1094, 911)
        self.MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Conimal = QtWidgets.QPushButton(self.centralwidget)
        self.Conimal.setGeometry(QtCore.QRect(370, 250, 351, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conimal.sizePolicy().hasHeightForWidth())
        self.Conimal.setSizePolicy(sizePolicy)
        self.Conimal.setMinimumSize(QtCore.QSize(200, 200))
        self.Conimal.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Conimal.setToolTip("")
        self.Conimal.setAutoFillBackground(False)
        self.Conimal.setObjectName("Conimal")
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(self.MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    # def setupUi(self, MainWindow):

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Conimal.setText(_translate("MainWindow", "Status"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow(MainWindow)
#     # ui.setupUi()
#     MainWindow.show()
#     sys.exit(app.exec_())
